Work around MSVC compiler error
When "qMin(abs(value), 1.0f)" causes an error like
"""
    error C2782: 'const T &qMin(const T &, const T&)': template
    parameter 'T' is ambiguous
"""
we're pretty far out in the Twilight Zone.

A change like this should never be required.